apiVersion: v1
kind: PersistentVolume
metadata:
  name: a-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: b-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data2

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: c-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/data3
